# 1. 手动构建神经网络

In [8]:
import torch
# z = b + w1*x1 +w2*x2, x*w
x = torch.tensor([[1, 0, 0], [1, 1, 0], [1, 0, 1], [1, 1, 1]], dtype= torch.float32)
# 参数初始化
w = torch.tensor([-0.2, 0.15, 0.15], dtype= torch.float32)    # (b, w1, w2)
z = torch.tensor([[-0.2], [-0.05], [-0.05], [0.1]], dtype = torch.float32)
def LinearR(X, w):
    zhat = torch.mv(X, w)
    return zhat

zhat = LinearR(X= x, w= w)
z = z.view(4)
zhat
torch.allclose(z, zhat)

True

In [ ]:
# torch.tensor - 判断你输入的数据是什么类型，然后根据你输入的数据来确定张量数据类型
# torch.Tensor - 无论输入什么数据，都无脑使用float32

In [ ]:
# 定义张量一定要定义类型

In [ ]:
# float32可能会有细微误差，要提高精度可以用float64

In [ ]:
# allclose（）无限接近，忽略细微误差进行比较

# 2. 利用PyTorch构建神经网络

![Alt text](image.png)

接下来，我们使用nn.Linear来实现单层回归神经网络

In [11]:
import torch
torch.__version__

'2.0.1'

In [12]:
x = torch.tensor([[0, 0], [1, 0], [0, 1], [1, 1]], dtype= torch.float32)
x

tensor([[0., 0.],
        [1., 0.],
        [0., 1.],
        [1., 1.]])

In [14]:
# w
# 实例化nn.Linear
output = torch.nn.Linear(2, 1)      # 可以添加参数 bias = Flase,这样就可以控制不生成 b
# 2:上一层神经元个数（上一层神经元输入给本层神经元的个数）
# 1：本层神经元个数（接受传输数据的神经元个数）
# 自动生成了系数w 和偏置 b

zhat = output(x)
zhat

tensor([[-0.5637],
        [-1.1240],
        [ 0.0359],
        [-0.5245]], grad_fn=<AddmmBackward0>)

怎么样，代码是不是异常简单呢？但在这段代码中，却有许多细节需要声明：

*  nn.Linear是一个类，在这里代表了输出层，所以我使用output作为变量名，output = 的这一行相当于是类的实例化过程

*  实例化的时候，nn.Linear需要传入两个参数，分别是（上一层的神经元个数，这一层的神经元个数）。上一层是输入层，因此神经元个数由特征的个数决定（2个）。这一层是输出层，作为回归神经网络，输出层只有一个神经元。因此nn.Linear中输入的是（2， 1）

*  我们只定义了x, 没有定义w和b。所有nn.Module的子类，形如nn.XXX的层，都会在实例化的同时随机生成w和b的初始值。所以实例化后，我们就可以调用以下属性来查看生成的w和b：

In [15]:
output.weight

Parameter containing:
tensor([[-0.5603,  0.5996]], requires_grad=True)

In [16]:
output.bias

Parameter containing:
tensor([-0.5637], requires_grad=True)

*  由于w和b是随机生成的，所以同样的代码多次运行后的结果是不一致的。如果我们希望控制随机性，则可以使用torch中的random类。如下所示：

In [22]:
# 随机数种子
torch.random.manual_seed(420)       # 人为设置随机数种子,这样bias和w就固定了
output = torch.nn.Linear(2, 1)
output.weight

Parameter containing:
tensor([[ 0.4318, -0.4256]], requires_grad=True)

In [21]:
output.bias

Parameter containing:
tensor([0.6730], requires_grad=True)

* 由于不需要定义常量b，因此在特征张量中，也不需要留出与常数项相乘的X0的那一列。在输入数据时，我们只输入了两个特诊X1与X2

* 输入层只有一层，并且输入层的结构（神经元个数）由输入的特征张量X决定，因此在PyTorch中构筑神经网络时，不需要定义输入层

* 实例化后，将特征张量输入到实例化后的类中，即可得到输出层的输出结果