##### 一、什么是NumPy?
NumPy是一个用于处理数组的Python库
它也有在线性代数、傅里叶变换和矩阵领域工作的功能
NumPy由Travis oliphant于2005年创建。它是一个开源项目，你可以免费使用他
NumPy是Numerical Python 的缩写
* 在Python中，我们有列表，可以达到数组的目的，但他们的处理速度很慢
* NumPy旨在提供一个数组对象，它比传统的Python列表快50倍
* NumPy中的数组对象被称为ndarray,它提供了很多支持性的函数，使得使用ndarray非常容易
* 数组在数据科学中使用得非常频繁，速度和资源都非常重要

##### 二、为什么NumPy比列表更快
* 与列表不同，NumPy的数组被存储在内存中的一个连续位置，所以进程可以非常有效地访问和操作它们。
* 这种行为在计算机科学中被称为引用的位置性
* 这就是NumPy比列表快的主要原因。此外，它还被优化以适用于最新的GPU架构

##### 三、创建NumPy array 对象
NumPy用于处理数组，NumPy中的数组对象称为ndarray
* 我们可以通过将Python 列表传入np.array() 来创建一个NumPy数组（也就是强大的 ndarray）。在下面的例子里，创建出的数组如右边所示，通常情况下，我们希望NumPy为我们初始化数组的值，为此NumPy提供了诸如ones()，zeros()和random.random()之类的方法。我们只需传入元素个数即可：

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

print(np.ones(3))
print(np.zeros(3))
print(np.random.random(3))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1. 1. 1.]
[0. 0. 0.]
[0.80988352 0.74315689 0.4374147 ]


##### 四、数组的算术运算
让我们创建两个NumPy数组，分别称为data和ones。
若要计算两个数组的加法，只需简单地敲入data + ones,就可以实现对应位置上的数据相加的操作，这种操作比循环读取数组的方法代码实现更加简洁。


In [4]:
data = np.array([1, 2])
ones = np.ones(2)
data + ones

array([2., 3.])

当然，在此基础上举一反三，也可以实现减法、乘法和除法等操作：

In [5]:
data - ones

array([0., 1.])

In [6]:
data * data

array([1, 4])

In [7]:
data / data

array([1., 1.])

许多情况下，我们希望进行数组和单个数值的操作（也称作向量和标量之间的操作）。比如：如果数组表示的是以英里为单位的距离，我们的目标是将其转换为公里数。可以简单的写作data * 1.6：

In [8]:
data * 1.6

array([1.6, 3.2])

NumPy通过数组广播（broadcasting）知道这种操作需要和数组的每个元素相乘。

##### 五、数组的切片操作
我们可以像python列表操作那样对NumPy数组进行索引和切片，如下图所示：


In [11]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [13]:
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])

1
2
[1 2]
[2 3]


##### 六、聚合函数
NumPy为我们带来的便利还有聚合函数，聚合函数可以将数据进行压缩，统计数组中的一些特征值：


In [14]:
print(data.max())
print(data.min())
print(data.sum())

3
1
6


除了min，max和sum等函数，还有mean（均值），prod（数据乘法）计算所有元素的乘积，std（标准差），等等。上面的所有例子都在一个维度上处理向量。除此之外，NumPy之美的一个关键之处是它能够将之前所看到的所有函数应用到任意维度上。


##### 七、NumPy中的矩阵操作

##### 创建矩阵：
我们可以通过将二维列表传给Numpy来创建矩阵。


In [16]:
data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

除此外，也可以使用上文提到的ones()、zeros()和random.random()来创建矩阵，只需传入一个元组来描述矩阵的维度：


In [18]:
print(np.ones((3,2)))
print()
print(np.zeros((3,2)))
print()
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[0.15979618 0.03715291]
 [0.17735875 0.13507302]
 [0.47009019 0.61743279]]


##### 矩阵的乘法

In [20]:
data_1 = np.array([[1, 2, 3], [4, 5, 6]])
data_2 = np.array([[2, 5, 8 ], [3, 7, 9], [1, 2, 5]])
data_2


array([[2, 5, 8],
       [3, 7, 9],
       [1, 2, 5]])

In [21]:
data_3 = data_1.dot(data_2)
data_3

array([[ 11,  25,  41],
       [ 29,  67, 107]])

##### 数据的切片

In [22]:
data_2 = np.array([[2, 5, 8 ], [3, 7, 9], [1, 2, 5]])
print(data_2[0,0])
print()
print(data_2[1:3])
print()
print(data_2[0:3, 0])

2

[[3 7 9]
 [1 2 5]]

[2 3 1]


我们可以像聚合向量一样聚合矩阵：


In [23]:
print(data_2.max())
print()
print(data_2.min())
print()
print(data_2.sum())

9

1

42


不仅可以聚合矩阵中的所有值，还可以使用axis参数指定行和列的聚合：

![Alt text](image-5.png)

##### 矩阵的转置和重构
处理矩阵时经常需要对矩阵进行转置操作，常见的情况如计算两个矩阵的点积。NumPy数组的属性T可用于获取矩阵的转置。

![Alt text](image-6.png)

在较为复杂的用例中，你可能会发现自己需要改变某个矩阵的维度。这在机器学习应用中很常见，例如模型的输入矩阵形状与数据集不同，可以使用NumPy的reshape()方法。只需将矩阵所需的新维度传入即可。也可以传入-1，NumPy可以根据你的矩阵推断出正确的维度：

![Alt text](image-7.png)

上文中的所有功能都适用于多维数据，其中心数据结构称为ndarray（N维数组）。

![Alt text](image-8.png)

很多时候，改变维度只需在NumPy函数的参数中添加一个逗号，如下图所示：

![Alt text](image-9.png)